// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vaxi4_lite_top.cpp"
#include "Vaxi4_lite_top__Trace.cpp"
#include "Vaxi4_lite_top__Slow.cpp"
#include "Vaxi4_lite_top__Syms.cpp"
#include "Vaxi4_lite_top__Trace__Slow.cpp"
